base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/general_dataset.yaml',
    './model_config/general_model.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_checkpoint_path: ''

run_status: 'train'
trainer:
  type: general
  model_name: 'general'
