base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/mae_dataset.yaml',
    './model_config/mae_vit_base_p16.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_or_finetune_checkpoint: ''

run_status: 'train'
trainer:
  type: mim
  model_name: 'mae'
