base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/bert_dataset.yaml',
    './model_config/bert_tiny_uncased.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_checkpoint_path: ''

run_status: 'train'
trainer:
  type: mlm
  model_name: 'bert'
