model:
  arch:
    type: T5ModelForGeneration
  model_config:
    attention_probs_dropout_prob: 0.1
    batch_size: 1
    beam_width: 4
    do_sample: false
    eos_token_id: 1
    has_relative_bias: true
    hidden_act: relu
    hidden_dropout_prob: 0.1
    hidden_size: 512
    initializer_range: 0.02
    intermediate_size: 2048
    is_encoder_decoder: true
    label_smoothing: 0.1
    length_penalty_weight: 1.0
    max_decode_length: 128
    max_length: 32
    max_position_embeddings: 1024
    num_heads: 8
    num_hidden_layers: 6
    repetition_penalty: 1
    scale_output: true
    seq_length: 1024
    top_k: 1
    top_p: 0.95
    type: T5Config
    vocab_size: 32128
