base_config: [
    '../__base__.yaml',
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/vit_dataset.yaml',
    './model_config/vit_base_p16.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_or_finetune_checkpoint: ''

run_mode: 'train'
trainer:
  type: image_classification
  model_name: 'vit'


