train_dataset: &train_dataset
  data_loader:
    type: ImageFolderDataset
    dataset_dir: "/data/imageNet-1k/train"
    num_parallel_workers: 8
    shuffle: True
    num_samples: 1000
  transforms:
    - type: RandomCropDecodeResize
      size: 224
      scale: [0.2, 1.0]
    - type: RandomHorizontalFlip
      prob: 0.5
    - type: Normalize
      mean: [123.675, 118.575, 103.53]
      std: [58.395, 62.22, 57.375]
    - type: HWC2CHW
#  mask_policy:
#    type: MaeMask
#    input_size: 224
#    model_patch_size: 16
#    mask_ratio: 0.75
  input_columns: ["image"]
  output_columns: [ "image" ]
  column_order: [ "image" ]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 128
  repeat: 1
  numa_enable: False
  prefetch_size: 30

train_dataset_task:
  type: MIMDataset
  dataset_config: *train_dataset
