# runner config
runner_config: &runner_config
  epoch: 800
  batch_size: 64
  image_size: 224
  sink_mode: True
  per_epoch_size: 0
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0
  load_checkpoint:

runner_wrapper:
  loss_scale:
    type: FixedLossScaleUpdateCell
    loss_scale_value: 1024
  train_one_step:
    type: TrainOneStepWithClipGNAndEMA
    use_ema: False
    ema_decay: 0.9999
    use_clip_grad: True
    clip_norm: 5.0

# optimizer
optimizer:
  type: AdamWeightDecay
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001 # 1e-8
  weight_decay: 0.05

# lr sechdule
lr_schedule:
  type: WarmUpCosineDecayV1
  max_lr: 0.00015
  min_lr: 0.
  start_warmup_lr: 0.
  warmup_steps: 40
  decay_steps: 100

callbacks:
  - type: LossMonitorAICC
  - type: SummaryMonitorAICC
    keep_default_action: True
  - type: CheckpointMointorAICC
    runner_config: *runner_config
    prefix: "xformer"
    save_checkpoint_steps: 100
    integrated_save: True
    async_save: False
  - type: ObsMonitorAICC