base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/bert_cluener_dataset.yaml',
    './model_config/ner_bert_base_chinese.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 42
resume_or_finetune_checkpoint: ''

run_mode: 'train'
trainer:
  type: NameEntityRecognitionTrainer
  model_name: bert_token_classification
