seed: 0
auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: False
profile_communication: False
profile_memory: True

use_parallel: False

# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 1        # num of epoch intervals between each eval, 1 means eval on every epoch end.

layer_scale: False
layer_decay: 0.65

lr_scale: False
lr_scale_factor: 256

micro_batch_interleave_num: 1

output_dir: './output'  # 当前不支持自定义修改，请勿修改该默认值
resume_or_finetune_checkpoint: ''

eval_callbacks:
  - type: ObsMonitor

# cfts init config
aicc_config:
  obs_path: "Please input obs url on AICC platform."
  upload_frequence: 1
  keep_last: False
