# ==== model config ====
model:
  model_config:
    type: GLMConfig
    vocab_size: 130528
    hidden_size: 4096
    num_layers: 28
    num_attention_heads: 32
    inner_hidden_size: 16384
    seq_length: 512  # 推理时, 输入pad到的长度, model里的最大句长
    embedding_dropout_prob: 0.0
    attention_dropout_prob: 0.0
    output_dropout_prob: 0.0
    hidden_size_per_attention_head: # default "None" means hidden-size/num-attention-heads.
    layernorm_order: "post"
    layernorm_epsilon: 1.0e-5
    use_final_layernorm: True
    use_past: False
    phase: 'train'
    activation_func: 'GELU'
    position_encoding_2d: True
    params_dtype: "float16"
    layernorm_dtype: "float32"
    softmax_dtype: "float32"
    compute_dtype: "float16"
    bos_token_id: 130004
    eos_token_id: 130005
    mask_token_id: 130000
    gmask_token_id: 130001
    pad_token_id: 3
    max_decode_length: 2048  # The maximum length of the generated words.
    repetition_penalty: 1
    is_enhanced_encoder: True
    checkpoint_name_or_path: "glm_6b"
  arch:
    type: GLMForPreTraining # 1. GLMChatModel for eval; 2.GLMTrainModel for train 3. GLMTrainModelWithLora

processor:
  return_tensors: ms
  tokenizer:
    type: ChatGLMTokenizer
    bos_token: '<sop>'
    eos_token: '<eop>'
    end_token: '</s>'
    mask_token: '[MASK]'
    gmask_token: '[gMASK]'
    padding_side: 'left'
    pad_token: '<pad>'
    unk_token: '<unk>'
  type: GLMProcessor

# ==== dataset config ====
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: True
  input_columns: ["input_ids", "label", "position_ids", "attention_mask"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 1
  repeat: 1
  numa_enable: False
  prefetch_size: 1

train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset

eval_dataset: &eval_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: True
  input_columns: ["input_ids", "label"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  batch_size: 1
  repeat: 1
  numa_enable: False
  prefetch_size: 1

eval_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *eval_dataset

# ==== context config ====
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  enable_graph_kernel: False
  graph_kernel_flags: "--disable_expand_ops=Softmax,Dropout --enable_parallel_fusion=true --reduce_fuse_depth=8 --enable_auto_tensor_inplace=true"
  max_call_depth: 10000
  max_device_memory: "25GB"
  save_graphs: False
  save_graphs_path: "./graph"
  device_id: 0

# parallel config
parallel:
  parallel_mode: 1 # 0-dataset, 1-semi, 2-auto, 3-hybrid
  gradients_mean: False
  loss_repeated_mean: True
  enable_alltoall: False
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: False  # optimizer shard
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"

moe_config:
  expert_num: 1
  capacity_factor: 1.05
  aux_loss_factor: 0.05
  num_experts_chosen: 1

recompute_config:
  recompute: False
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: False

parallel_config:
  data_parallel: 1
  model_parallel: 8
  pipeline_stage: 1
  expert_parallel: 1
  optimizer_shard: False  # optimizer shard
  micro_batch_num: 1
  vocab_emb_dp: True
  gradient_aggregation_group: 4

# ==== runner config ====
runner_config:
  epochs: 1
  batch_size: 8
  sink_mode: True
  sink_size: 1
  per_epoch_size: 4
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0

runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense:
    type: DynamicLossScaleUpdateCell
    loss_scale_value: 4294967296
    scale_factor: 2
    scale_window: 1000
  use_clip_grad: True

# optimizer
optimizer:
  type: FusedAdamWeightDecay
  beta1: 0.9
  beta2: 0.95
  eps: 0.00000001 # 1e-8
  weight_decay: 0.1

# lr sechdule
lr_schedule:
  type: polynomial
  learning_rate: 0.00005
  lr_end: 0.000001
  warmup_steps: 2000
  total_steps: -1 # -1 means it will load the total steps of the dataset

callbacks:
  - type: MFLossMonitor
  - type: SummaryMonitor
    keep_default_action: True
  - type: CheckpointMointor
    prefix: "glm-6b"
    save_checkpoint_steps: 500
    integrated_save: False
    async_save: False
  - type: ObsMonitor

auto_tune: False
autotune_per_step: 10

profile: False
profile_start_step: 1
profile_stop_step: 10
init_start_profile: True
profile_communication: True
profile_memory: True

use_parallel: False

micro_batch_interleave_num: 1

seed: 0
resume_or_finetune_checkpoint: "" # path or direction of resume checkpoint.


run_mode: 'train'
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'glm_6b'

metric:
  type: ADGENMetric
  vocab_file: "ice_text.model" # Path of vocab file.

generate:
  max_decode_length: 2048
  top_p: 0.7
  do_sample: False