model:
  model_config:
    type: BertConfig
    use_one_hot_embeddings: False
    num_labels: 1
    dropout_prob: 0.1
    batch_size: 16
    seq_length: 128
    vocab_size: 30522
    embedding_size: 768
    num_layers: 12
    num_heads: 12
    expand_ratio: 4
    hidden_act: "gelu"
    post_layernorm_residual: True
    hidden_dropout_prob: 0.1
    attention_probs_dropout_prob: 0.1
    max_position_embeddings: 128
    type_vocab_size: 2
    initializer_range: 0.02
    use_relative_positions: False
    use_past: False
    use_moe: False
    checkpoint_name_or_path: ""
  arch:
    type: BertNetworkWithLoss