# runner config
runner_config:
  epochs: 100
  batch_size: 32
  image_size: 224
  sink_mode: True
  per_epoch_size: -1
  initial_epoch: 0
  has_trained_epoches: 0
  has_trained_steps: 0
  num_classes: 1000
  layer_decay: 0.65

runner_wrapper:
  type: TrainOneStepWithClipGN
  scale_sense:
    type: FixedLossScaleUpdateCell
    loss_scale_value: 1024

# optimizer
optimizer:
  type: AdamWeightDecay
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001 # 1e-8
  weight_decay: 0.05

# lr sechdule
lr_schedule:
  type: WarmUpCosineDecayV1
  base_lr: 0.0005
  min_lr: 0.000001
  warmup_lr: 0.
  warmup_epochs: 5

callbacks:
  - type: MFLossMonitor
  - type: SummaryMonitor
    keep_default_action: True
  - type: CheckpointMointor
    prefix: "mindformers"
    save_checkpoint_steps: 100
    integrated_save: True
    async_save: False
#  - type: ObsMonitor

metric:
  type: Accuracy
  eval_type: classification