base_config: [
    '../__base__.yaml',
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/swin_dataset.yaml',
    './model_config/swin_base_p4w7.yaml' ]

profile: False
use_parallel: False

# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: True
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 1        # num of epoch intervals between each eval, 1 means eval on every epoch end.

layer_scale: True
layer_decay: 0.9

lr_scale: True
lr_scale_factor: 512

seed: 0
resume_or_finetune_checkpoint: '' # Input ckpt file path here

run_mode: 'train'
trainer:
  type: image_classification
  model_name: 'swin_base_p4w7'
