base_config: [
    './model_config/clip_vit_b_32.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_checkpoint_path: ''

run_status: 'predict'
trainer:
  type: mim
  model_name: 'mae'