base_config: [
    './task_config/context.yaml',
    './task_config/runner.yaml',
    './task_config/clip_cafir_dataset.yaml',
    './model_config/clip_vit_b_32.yaml',
    '../__base__.yaml' ]

profile: False
use_parallel: False

seed: 0
resume_checkpoint_path: ''

run_status: 'eval'
trainer:
  type: zero_shot_image_classification
  model_name: 'clip'